// Code generated by goctl. DO NOT EDIT!
// Source: check.proto

//go:generate mockgen -destination ./check_mock.go -package checkclient -source $GOFILE

package checkclient

import (
	"context"

	"bookstore/rpc/check/check"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	CheckReq  = check.CheckReq
	CheckResp = check.CheckResp

	Check interface {
		Check(ctx context.Context, in *CheckReq) (*CheckResp, error)
	}

	defaultCheck struct {
		cli zrpc.Client
	}
)

func NewCheck(cli zrpc.Client) Check {
	return &defaultCheck{
		cli: cli,
	}
}

func (m *defaultCheck) Check(ctx context.Context, in *CheckReq) (*CheckResp, error) {
	client := check.NewCheckClient(m.cli.Conn())
	return client.Check(ctx, in)
}
